import React, { useState } from "react";
import { useAuth, useUser } from "@clerk/nextjs";

import "bootstrap/dist/css/bootstrap.min.css";
import {
  Container,
  Nav,
  Navbar,
  Card,
  Row,
  Col,
  Button,
  Form,
} from "react-bootstrap";
import ExpenseModal from "@/components/ExpenseModal";
import Head from "next/head";
import { useRouter } from "next/router";

export default function NewPlanPage() {
  const [showModal, setShowModal] = useState(false);
  const [selectedExpense, setSelectedExpense] = useState("");

  const handleExpenseClick = (expense) => {
    setSelectedExpense(expense);
    setShowModal(true);
  };
  
  const handleModalClose = () => {
    setShowModal(false);
    setSelectedExpense("");
  };
  return (
    <>
      <ExpenseModal
        show={showModal}
        expense={selectedExpense}
        handleClose={handleModalClose}
      />
      <Head>
        <title>New Plan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/duckget-logo.png" />
      </Head>
      <div style={{ minHeight: "100vh", backgroundColor: "#E4E4E4" }}>
        <Container fluid className="p-0">
        <div
            className="p-4 w-100 white-box-container"
            style={{ height: "calc(100vh - 130px)", overflowY: "scroll" }}
          >
            <Row>
              <Col xs={3}>
                <img src="/back-arrow.png" alt="back arrow" />
              </Col>
              <Col xs={6}>
                <h1 className="text-center text-wrap" style={{color: '#472B00'}}>Set New Plan</h1>
              </Col>
              <Col
                xs={3}
                className="d-flex justify-content-end align-items-center"
              >
                <img
                  src="/duck.png"
                  alt="duck"
                  className="img-fluid"
                  style={{ maxWidth: "150px" }}
                />
              </Col>
            </Row>
            <Row>
              <Col>
                <Form.Group controlId="planName">
                  <Form.Label><span className="light-brown">Name</span></Form.Label>
                  <Form.Control
                    type="text"
                    style={{
                      background: "#F7E7D5",
                      borderRadius: "11px",
                    }}
                  />
                  <Form.Label><span className="light-brown">Projected Yearly Income</span></Form.Label>
                  <Form.Control
                    type="text"
                    style={{
                      background: "#F7E7D5",
                      borderRadius: "11px",
                    }}
                  />
                  <Form.Label><span className="light-brown">Location</span></Form.Label>
                  <Form.Control
                    type="text"
                    style={{
                      background: "#F7E7D5",
                      borderRadius: "11px",
                    }}
                  />
                </Form.Group>
              </Col>
            </Row>
            <Row>
              <Col>
                <h2 className="text-center mb-4">Expenses</h2>
              </Col>
            </Row>
            <Row>
              <Col className="text-center">
                <img
                  src="/auto.png"
                  alt="Auto"
                  className="img-fluid m-2"
                  style={{ maxWidth: "150px", cursor: "pointer" }}
                  onClick={() => handleExpenseClick("Auto")}
                />
                <img
                  src="/home.png"
                  alt="Home"
                  className="img-fluid m-2"
                  style={{ maxWidth: "150px", cursor: "pointer" }}
                  onClick={() => handleExpenseClick("Home")}
                />
                <img
                  src="/other.png"
                  alt="Other"
                  className="img-fluid m-2"
                  style={{ maxWidth: "150px", cursor: "pointer" }}
                  onClick={() => handleExpenseClick("other")}
                />
              </Col>
            </Row>
          </div>
        </Container>
        <div className="p-3 text-center">
          <Button
            className="d-block mx-auto"
            style={{
              backgroundColor: "#47B1ED",
              boxShadow: "0px 4px 4px rgba(0, 0, 0, 0.25)",
              borderRadius: "10px",
              width: "30%",
              height: "80px",
              border: "none",
              marginBottom: "30px",
            }}
          >
            <h1>Save</h1>
          </Button>
        </div>
      </div>
    </>
  );
}
