import React, { useState } from "react";
import { useAuth, useUser } from "@clerk/nextjs";

import "bootstrap/dist/css/bootstrap.min.css";
import {
  Container,
  Nav,
  Navbar,
  Card,
  Row,
  Col,
  Button,
  Form
} from "react-bootstrap";
import Navigation from "@/components/Navigation";
import Head from "next/head";
import { useRouter } from "next/router";

export default function NewPlanPage() {
  return (
    <>
      <Head>
        <title>New Plan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/duckget-logo.png" />
      </Head>
      <div style={{ minHeight: "100vh", backgroundColor: "#E4E4E4" }}>
        <Container fluid className="p-0">
          <div
            className="p-4 w-100 white-box-container"
            style={{ height: "calc(100vh - 130px)", overflowY: "scroll" }}
          >
            <Row>
              <Col xs={2}>
                <img src="/back-arrow.png" alt="back arrow" />
              </Col>
              <Col xs={8}>
                <h1 className="text-center">Set New Plan</h1>
              </Col>
              <Col xs={2}>
                <img src="/duck.png" alt="duck" />
              </Col>
            </Row>
            <Row>
              <Col>
                <Form.Group controlId="planName">
                  <Form.Label>Name of Plan</Form.Label>
                  <Form.Control
                    type="text"
                    style={{
                      background: "#F7E7D5",
                      borderRadius: "11px",
                    }}
                  />
                </Form.Group>
              </Col>
            </Row>
            {/* Your form components would go here */}
          </div>
        </Container>
        <div className="p-3 text-center">
          <Button
            className="d-block mx-auto"
            style={{
              backgroundColor: "#47B1ED",
              boxShadow: "0px 4px 4px rgba(0, 0, 0, 0.25)",
              borderRadius: "10px",
              width: "30%",
              height: "80px",
              border: "none",
              marginBottom: "30px"
            }}
          >
            <h1>Save</h1>
          </Button>
        </div>
      </div>
    </>
  );
}
